jobs:
  - name: deploy
    type: runSh
    steps:
      - IN: devtac-shippable_runCI
      - TASK:
          name: check_images
          script:
            - echo "Checking available docker images"
    on_start:
      NOTIFY: Slack (DevTac)
    on_success:
      NOTIFY: Slack (DevTac)

  - name: devtac-shippable_runCI
      type: runCI
      steps:
        - OUT: myRepo
          replicate: devtac-shippable_ciRepo